item {
	id: 1
	name: 'canis_major'
}

item {
	id: 2
	name: 'canis_minor'
}

item {
	id: 3
	name: 'cassiopeia'
}

item {
	id: 4
	name: 'coma_berenices'
}

item {
	id: 5
	name: 'corona_borealis'
}

item {
	id: 6
	name: 'cygnus'
}

item {
	id: 7
	name: 'delphinus'
}

item {
	id: 8
	name: 'gemini'
}

item {
	id: 9
	name: 'hercules'
}

item {
	id: 10
	name: 'libra'
}

item {
	id: 11
	name: 'lyra'
}

item {
	id: 12
	name: 'sagitta'
}

item {
	id: 13
	name: 'ursa_minor'
}

item {
	id: 14
	name: 'vulpecula'
}
